# Generated by Django 5.0.1 on 2024-01-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightNo', models.TextField(max_length=100)),
                ('To', models.TextField(max_length=100)),
                ('From', models.TextField(max_length=100)),
                ('Departure', models.TextField(max_length=100)),
                ('Arrival', models.TextField(max_length=100)),
            ],
        ),
    ]
