# Generated by Django 5.0.1 on 2024-01-28 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0002_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
