# Generated by Django 5.0.1 on 2024-01-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0003_flights_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('CNIC', models.CharField(max_length=100)),
                ('Passport_Number', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=10)),
            ],
        ),
    ]
