# Generated by Django 5.0.1 on 2024-01-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0004_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passenger_Name', models.CharField(max_length=100)),
                ('Passport_Number', models.CharField(max_length=15)),
                ('CNIC', models.CharField(max_length=10)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Departure', models.DateField()),
                ('Booked_By', models.CharField(max_length=50)),
                ('Booking_Time', models.TimeField()),
            ],
        ),
    ]
