# Generated by Django 5.0.1 on 2024-01-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0005_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='CNIC',
            field=models.CharField(max_length=100),
        ),
    ]
