# Generated by Django 5.0.1 on 2024-02-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0006_alter_bookings_cnic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Users',
        ),
    ]
