# Generated by Django 5.0.1 on 2024-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0008_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='DOB',
            field=models.DateField(max_length=100),
        ),
    ]
