# Generated by Django 5.0.1 on 2024-02-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0009_alter_members_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='DOB',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='Shift',
            field=models.CharField(max_length=20),
        ),
    ]
