# Generated by Django 5.0.1 on 2024-02-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0010_alter_members_address_alter_members_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
