# Generated by Django 5.0.1 on 2024-02-02 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0011_alter_members_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
