# Generated by Django 5.0.1 on 2024-02-05 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0012_members_password_alter_members_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Joining_Date',
            field=models.DateField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
