# Generated by Django 5.0.1 on 2024-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0013_members_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Arrival',
            field=models.TimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Departure',
            field=models.TimeField(max_length=100),
        ),
    ]
