# Generated by Django 5.0.1 on 2024-02-07 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0014_alter_flights_arrival_alter_flights_departure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='Date',
            new_name='FlightDate',
        ),
        migrations.AddField(
            model_name='flights',
            name='Fare_Business',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flights',
            name='Fare_Economy',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
