# Generated by Django 5.0.1 on 2024-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsApp', '0015_rename_date_flights_flightdate_flights_fare_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='FlightStatus',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
